### ISSUE TITLE
style Have no effect on the content before the update

### ISSUE THREAD

**Issue by ReAlign** [Fandom-OSS/quill-blot-formatter#1]
![](http://olz3b8fm9.bkt.clouddn.com/17-12-27/29577282.jpg)

**Comment by ReAlign** [comment]
added:

When I change the image size, how do I trigger the event?

the events how to use？

**Comment by nmonterroso** [comment]
Sorry for the late response.

I'm a bit unclear on what you're expecting here. Can you provide more info on what you're expecting? From the demo it looks like the `style` attribute isn't there when it probably should be. Can you provide a demo of the issue so I can take a look?

**Comment by nmonterroso** [comment]
Closing since I need more info
