### ISSUE TITLE
width and height are being removed when render in Editor

### ISSUE THREAD

**Issue by nguyenpc** [Fandom-OSS/quill-blot-formatter#10]
I've followed the instruction in the readme. It works well with resizing. However, after rendering from saved HTML, width and height of iframe seem being removed and the video size (the same issue for image) is back to default size 300x150. Do we have any solutions for this case?

Thank you.

**Comment by nguyenpc** [comment]
Seems the issue caused by react-quill. this should be closed

**Comment by typescript-any** [comment]
I am facing same issue can you provide the solution
