### ISSUE TITLE
Is it possible to define max width/height on resizing?

### ISSUE THREAD

**Issue by ninbit** [Fandom-OSS/quill-blot-formatter#13]
As title said, is that possible? It would be good if we are able to define max width or height on resizing

**Comment by kanwisher** [comment]
you could just set a style in quill like so:

 .ql-editor img {
    max-width: 400px; // your value here
    height: auto;
}

then quill-blot-formatter appears to manage this size limitation appropriately

**Comment by ninbit** [comment]
Simple is best! Thank you for your solution. Additionally there may be a need of adding `!important` attribute in order to ignore the rule of quill css, `max-width: 100%;`
