### ISSUE TITLE
The proper way to get & set quill contents data

### ISSUE THREAD

**Issue by akupiec** [Fandom-OSS/quill-blot-formatter#3]
Blot formatter plugin do not write styles in to quill content data.

**Reproduction steps:**
1. create quill instance with plugin 
```
var quill = new Quill('#quill', {
            modules: {
                blotFormatter: {},
            },
        });

```
2. create event handler on blur 
```
quill.on('selection-change', (range, oldRange, source) => {
        if (range === null && oldRange !== null) {
            console.log(quill.getContents())
      }
});
```
3. add any image to quill and resize it .
4. de focus quill to trigger selection-change event

**Actual result:**
Quill returns blob without image atributes

**Expected result:**
Resizing should update quill model state and be available through function getContents()

**Comment by nmonterroso** [comment]
Sorry for the late response.

It'd make sense for it to work this way, or have a documented way to get at this information. I'll take a look next week.

**Comment by nmonterroso** [comment]
@akupiec - can you try with the latest (v1.0.4) and let me know if this works as you'd expect?

You should now be seeing `selection-change` events with `attributes` properly filled out for the image containing the delta. This should also work for `text-change` events as well.

**Comment by akupiec** [comment]
@nmonterroso thank you for new version I will check it till end of the week, and then I will let you known.

**Comment by nmonterroso** [comment]
Closing since over a month with no comment

**Comment by armellarcier** [comment]
I'm facing the same issue
