### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by JoshuaRogan** [Fandom-OSS/quill-blot-formatter#4]
Looks like webpack bin has been shut down: https://twitter.com/christianalfoni/status/964212636027183106

**Comment by nmonterroso** [comment]
Ah, good call. Moved to codesandbox: https://codesandbox.io/s/4wnwllnnl9. I'll update the README

**Comment by nmonterroso** [comment]
OK, `v1.0.5` is live on npmjs with an updated readme. Thanks!
